[package]
name = "asinki/boilerplate-experience"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
private = true

[place]
shared-packages = "game.ReplicatedStorage.Packages"

[dependencies]
Console = "4x8matrix/console@2.1.1"
CameraProfiler = "4x8matrix/camera-profiler@1.0.6"
RbxControls = "4x8matrix/roblox-controls@0.1.0"
Runtime = "4x8matrix/runtime@1.0.0"
Sift = "csqrl/sift@0.0.9"
Signal = "sleitnick/signal@2.0.1"
Trove = "sleitnick/trove@1.4.0"
Component = "sleitnick/component@2.4.8"
Promise = "evaera/promise@4.0.0"
UIParticle = "4x8matrix/ui-particle-fork@3.0.2"

[server-dependencies]
DataKeep = "noahrepublic/datakeep@4.1.0"