name: Production-CD

on:
  push:
    branches:
      - Master
  workflow_dispatch:

jobs:
  Production-CD:
    name: Production CD
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: ok-nick/setup-aftman@v0.4.2
    - name: Deploy to Production
      run: rojo upload --api_key "$RBX_KEY" --universe_id "$PRODUCTION_UNIVERSE_ID" --asset_id "$PRODUCTION_ID"
      env:
        RBX_KEY: ${{ secrets.RBX_KEY }}
        PRODUCTION_UNIVERSE_ID: ${{ secrets.PRODUCTION_UNIVERSE_ID }}
        PRODUCTION_ID: ${{ secrets.PRODUCTION_ID }}